const fields = ["heliusKey","routeApi","frogTradeWallet","truenestTradeWallet","frogSignerToken","truenestSignerToken","frogDeposit","truenestDeposit","frogWallet","frogMax","frogMode","truenestWallet","truenestMax","truenestMode"];
const $ = (id) => document.getElementById(id);
const money = (v) => Number(v || 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
function payload(){const data={};fields.forEach(id=>data[id]=$(id).value.trim());return data;}
function ready(s){return Boolean(s.heliusKey&&s.routeApi&&s.frogTradeWallet&&s.truenestTradeWallet&&s.frogSignerToken&&s.truenestSignerToken)}
function log(lines){$("activityLog").innerHTML="";(lines||[]).forEach(x=>{const li=document.createElement("li");li.textContent=x;$("activityLog").appendChild(li);});}
function render(state){const s=state.settings||{}, p=state.profiles||{};fields.forEach(id=>{if(s[id]&&document.activeElement!==$(id)) $(id).value=s[id];});const ok=ready(s);$("frogStart").disabled=!ok||p.frog?.running;$("truenestStart").disabled=!ok||p.truenest?.running;$("frogStop").disabled=!p.frog?.running;$("truenestStop").disabled=!p.truenest?.running;$("frogProfit").textContent=money(p.frog?.profit);$("truenestProfit").textContent=money(p.truenest?.profit);$("frogBalance").textContent="Deposit: "+money(s.frogDeposit);$("truenestBalance").textContent="Deposit: "+money(s.truenestDeposit);if(!ok){$("engineStatus").textContent="Engine Room needs keys";$("engineSubtext").textContent="Add all boxes, then Save.";const miss=[];if(!s.heliusKey)miss.push("Waiting for Helius API key.");if(!s.routeApi)miss.push("Waiting for Jupiter route API.");if(!s.frogTradeWallet)miss.push("Waiting for Frog wallet.");if(!s.truenestTradeWallet)miss.push("Waiting for Truenest wallet.");if(!s.frogSignerToken)miss.push("Waiting for Frog signer token.");if(!s.truenestSignerToken)miss.push("Waiting for Truenest signer token.");log(miss);return;}const running=[];if(p.frog?.running)running.push("Frog beginner is running.");if(p.truenest?.running)running.push("Truenest Big Win is running.");$("engineStatus").textContent=running.length?"Copy engine running":"Engine ready";$("engineSubtext").textContent=running.length?"Render is watching selected wallets.":"Press Start on the account you want.";log(state.activity?.length?state.activity:["Ready."]);}
async function api(path,opt={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opt});if(!r.ok)throw new Error(await r.text());return r.json();}
async function refresh(){try{render(await api("/api/status"));}catch{$("engineStatus").textContent="Backend not connected";$("engineSubtext").textContent="Deploy on Render to make buttons live.";log(["Backend is not running yet."]);}}
async function save(){render({settings:payload(),profiles:{},activity:["Saving Engine Room..."]});render(await api("/api/settings",{method:"POST",body:JSON.stringify(payload())}));}
async function start(profile){render(await api('/api/start/'+profile,{method:'POST'}));}
async function stop(profile){render(await api('/api/stop/'+profile,{method:'POST'}));}
$("saveSettings").addEventListener("click",save);fields.forEach(id=>$(id).addEventListener("input",()=>render({settings:payload(),profiles:{},activity:[]})));$("frogStart").onclick=()=>start("frog");$("frogStop").onclick=()=>stop("frog");$("truenestStart").onclick=()=>start("truenest");$("truenestStop").onclick=()=>stop("truenest");refresh();setInterval(refresh,5000);
